### ISSUE TITLE
Typo in Storing Secrets post

### ISSUE THREAD

**Issue by softmoth** [ItalyPaleAle/WithBlueInk#12]
The penultimate sentence at https://github.com/ItalyPaleAle/WithBlueInk/blame/master/content/posts/2021-05-07-storing-secrets-and-passwords-in-git-is-bad/index.md#L136 has some important words removed, probably by an editing mistake. The intended meaning is unclear:
> Vaults may be able to keys and certain other secrets secrets automatically for you, for increased security

**Comment by ItalyPaleAle** [comment]
Oh thanks for pointing that out, and apologies for the mistake! It's missing the "rotate" word.
